services:
  - type: web
    name: lataifas-restaurant
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.25
      - key: NODE_ENV
        value: production
